/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from 'ethers';
import type { Provider } from '@ethersproject/providers';
import type { Y2KToken, Y2KTokenInterface } from '../Y2KToken';

const _abi = [
  {
    inputs: [],
    stateMutability: 'nonpayable',
    type: 'constructor',
  },
  {
    stateMutability: 'payable',
    type: 'fallback',
  },
  {
    stateMutability: 'payable',
    type: 'receive',
  },
];

export class Y2KToken__factory {
  static readonly abi = _abi;
  static createInterface(): Y2KTokenInterface {
    return new utils.Interface(_abi) as Y2KTokenInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): Y2KToken {
    return new Contract(address, _abi, signerOrProvider) as Y2KToken;
  }
}
